version: "3"

services:
  loki:
    image: grafana/loki
    extra_hosts: ['host.docker.internal:host-gateway']
    ports:
    - "3100:3100"
  grafana:
    image: grafana/grafana
    extra_hosts: ['host.docker.internal:host-gateway']
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    depends_on:
      - loki
  app:
    build: .
    logging:
      driver: loki
      options:
        loki-external-labels: container_name={{.Name}},app=demo
        loki-url: http://localhost:3100/loki/api/v1/push
    depends_on:
      - loki